### ISSUE TITLE
Core signature change causes compilation failure

### ISSUE THREAD

**Issue by terjeio** [Expatria-Technologies/grblhal_probe_plugin#1]
I am a bit unsure about the intention behind this code at line 241+:

        if(tool && !nvs_hardlimits && probe_protect_settings.flags.hardlimits){ //if the hard limits are not already enabled they need to be enabled.
            hal.limits.enable(settings.limits.flags.hard_enabled, true); // Change immediately. NOTE: Nice to have but could be problematic later.
        }

The second parameter is set true when homing is in progress and may disable limits regardless of the first parameter, the original use was for Trinamic driver code to enable sensorless homing and override limit switches inputs when homing. In the latest core version this parameter is now an axismask and is used by some drivers (will soon be all) to disable interrupts for limit switches during homing - but only for the switches used by the active homing cycle. If the intention was to _really_ enable hard limits at all times during probing then the correct way is to do the call like this: `hal.limits.enable(true, (axes_signals_t){0})` or more likely like this `hal.limits.enable(probe_protect_settings.flags.hardlimits, (axes_signals_t){0})`?. 
I have modified the code used by the Web Builder to always enable hard limits, I can provide a PR with the needed changes (there are two more calls to  `hal.limits.enable()`) - but should I use the first or second version above?

**Comment by andrewmarles** [comment]
I am just away from the PC, but the second version is probably what should be used.  The intent is to enable all axes hard limits when the probe protection hard limit flag is set.  This allows a user to connect the overtravel switch in a toolsetter to a limit input in series with a homing switch but not need to have hard limits enabled all the time.  I just enable them all to avoid consuming another $etting to select a specific input, but that might be a better option?

**Comment by andrewmarles** [comment]
@terjeio if you have your changes in a branch somewhere I can roll them in, back at the PC today.

**Comment by terjeio** [comment]
[PR](https://github.com/Expatria-Technologies/grblhal_probe_plugin/pull/2) committed.

FYI the init call is not yet in _plugins_init.h_, will add it in the next core commit.

In the readme you have this todo:

> Set jog exclusion zone around toolsetter.

In the latest commit I have added two new core entry points, `grbl.apply_jog_limits` and `grbl.check_travel_limits`. These defaults to core functions and can be overridden and/or extended by plugin code. Also note that the core jog `apply_jog_limits` implementation has been changed to clip the target to the work envelope instead of limiting to per axis max travel, multi-axis jogs will thus always travel in the same direction regardless of the start position.

**Comment by andrewmarles** [comment]
> [PR](https://github.com/Expatria-Technologies/grblhal_probe_plugin/pull/2) committed.
> 
> FYI the init call is not yet in _plugins_init.h_, will add it in the next core commit.
> 
> In the readme you have this todo:
> 
> > Set jog exclusion zone around toolsetter.
> 
> In the latest commit I have added two new core entry points, `grbl.apply_jog_limits` and `grbl.check_travel_limits`. These defaults to core functions and can be overridden and/or extended by plugin code. Also note that the core jog `apply_jog_limits` implementation has been changed to clip the target to the work envelope instead of limiting to per axis max travel, multi-axis jogs will thus always travel in the same direction regardless of the start position.

Yes, I have been following along the delta kinematics discussion and saw those changes to the travel limts.  Looks really useful.  Thank you for your attention on this PR.
